// <auto-generated />
using System;
using Company.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20220522172137_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Company.Models.Employee", b =>
                {
                    b.Property<long?>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("EmployeeId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar (60)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar (15)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar (15)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar (4)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar (10)");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime");

                    b.Property<string>("HomePhone")
                        .HasColumnType("nvarchar (24)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar (20)");

                    b.Property<string>("Notes")
                        .HasColumnType("ntext");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("image");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar (255)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar (10)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar (15)");

                    b.Property<int?>("ReportsTo")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar (30)");

                    b.Property<string>("TitleOfCourtesy")
                        .HasColumnType("nvarchar (25)");

                    b.HasKey("EmployeeId");

                    b.HasIndex(new[] { "LastName" }, "LastName");

                    b.HasIndex(new[] { "PostalCode" }, "PostalCodeEmployees");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Company.Models.Project", b =>
                {
                    b.Property<long>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ProjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProjectID"), 1L, 1);

                    b.Property<decimal>("Budjet")
                        .HasColumnType("DECIMAL");

                    b.Property<DateTime>("DateOfAdoption")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR (200)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("VARCHAR (20)");

                    b.HasKey("ProjectID");

                    b.HasIndex("ProjectID")
                        .IsUnique();

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
